In [3]:
#Crear un arreglo a partir de otro arreglo

import numpy as np

# Arreglo original
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("🔸 Arreglo original:")
print(arr)

# Sacamos una "rebanada" (view)
rebanada = arr[1:, :2]
print("\n🔹 Rebanada (view):")
print(rebanada)

# Modificamos la rebanada
rebanada[0, 0] = 100

print("\n⚠️ Arreglo original después de cambiar la rebanada:")
print(arr)

print("\n🔸 Rebanada actualizada:")
print(rebanada)

#Para no afectar todo, creamos una copia
arr2 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
rebanada_copia = arr2[1:, :2].copy()
print("\n🔹 Rebanada copia (copy):")
print(rebanada_copia)

# Modificamos la copia
rebanada_copia[0, 0] = 100

print("\n✅ Arreglo original después de cambiar la copia:")
print(arr2)

print("\n🔸 Copia actualizada (solo ella cambió):")
print(rebanada_copia)


🔸 Arreglo original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

🔹 Rebanada (view):
[[4 5]
 [7 8]]

⚠️ Arreglo original después de cambiar la rebanada:
[[  1   2   3]
 [100   5   6]
 [  7   8   9]]

🔸 Rebanada actualizada:
[[100   5]
 [  7   8]]

🔹 Rebanada copia (copy):
[[4 5]
 [7 8]]

✅ Arreglo original después de cambiar la copia:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

🔸 Copia actualizada (solo ella cambió):
[[100   5]
 [  7   8]]


In [11]:
#Crear secuencias, repeticiones y números aleatorios

#Sirve para crear una secuencia con paso fijo.
#np.arange(inicio, fin, paso)
import numpy as np
arr = np.arange(0, 10, 2)
print("np.arange(0, 10, 2)")
print(arr)
print()

#np.linspace()
#crea una cantidad exacta de números entre dos valores
#np.linspace(inicio, fin, cantidad)
arr = np.linspace(0, 10, 5)
print("np.linspace(0, 10, 5)")
print(arr)
print()


np.arange(0, 10, 2)
[0 2 4 6 8]

np.linspace(0, 10, 5)
[ 0.   2.5  5.   7.5 10. ]



In [19]:
#Crear arreglos de 1's y 0's
import numpy as np

a = np.zeros((3, 3))
print(a)
print()

b = np.ones((3, 3))
print(b)
print()

#Diagonales
np.fill_diagonal(a, 1)
print(a)
print()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [21]:
# Crear secuencias repetidas

#np.tile()
import numpy as np

a = np.array([1, 2, 3])
print("Original:", a)

# Repite el arreglo 2 veces
b = np.tile(a, 2)
print("Tile:", b)

#np.repeat()
c = np.repeat(a, 4)
print("Repeat:", c)


Original: [1 2 3]
Tile: [1 2 3 1 2 3]
Repeat: [1 1 1 1 2 2 2 2 3 3 3 3]


In [28]:
#Números aleatorios
import numpy as np

#np.random.rand()

print("np.random.rand()")
print()
x = np.random.rand() #Num aleatorio entre 0 y 1
print("Num aleatorio entre 0 y 1:    ",x)
print()

a = np.random.rand(5)#Si quiero 5 num aleatorios
print("5 num aleatorios:    ",a)
print()
m = np.random.rand(2, 3) #Matriz aleatoria de 2 filas y 3 columnas
print("Matriz aleatoria de 2 filas y 3 columnas:   ")
print(m)
print()

print("Un arreglo 3d")
n=np.random.rand(2,3,4)
print(n)
print()

#np.random.randn()
print("-"*30)
print("np.random.randn()")
print()

print("Genera num aleatorio, distribucion normal en forma de campana cuya medida normal es 0")
print("asi que todos los numeros estaran cerca del 0 pudiendo ser + o -")
print()
z = np.random.randn()
print(z)
print("Tiene la misma estructura que rand, asi que podemos hacer lo mismo")
print()
print("-"*30)
#np.random.randint()
print("np.random.randint()")
print("np.random.randint(inicio, fin, tamaño)")
q=np.random.randint(0, 10)
print(q)
q=np.random.randint(0, 10,2)
print(q)

print()
      

#np.random.choice()

np.random.rand()

Num aleatorio entre 0 y 1:     0.011913856125100764

5 num aleatorios:     [0.19648919 0.46424431 0.00121817 0.66702381 0.75823543]

Matriz aleatoria de 2 filas y 3 columnas:   
[[0.75451446 0.76157325 0.08410138]
 [0.70211814 0.62736554 0.82432076]]

Un arreglo 3d
[[[0.02513312 0.93227443 0.1234146  0.08080668]
  [0.67284586 0.22206678 0.66845002 0.79074001]
  [0.27791313 0.5614468  0.3883163  0.06755565]]

 [[0.60674926 0.40525696 0.58073668 0.29142004]
  [0.78280741 0.48726963 0.11958236 0.80651679]
  [0.72115164 0.38181514 0.66029522 0.83251778]]]

------------------------------
np.random.randn()

Genera num aleatorio, distribucion normal en forma de campana cuya medida normal es 0
asi que todos los numeros estaran cerca del 0 pudiendo ser + o -

-0.6030920483047012
Tiene la misma estructura que rand, asi que podemos hacer lo mismo

------------------------------
np.random.randint()
np.random.randint(inicio, fin, tamaño)
4
[1 0]



In [12]:
#Elección al azar

In [ ]:
#Semillas

In [ ]:
#Obtener valores únicos y frecuencias absolutas