In [3]:
#Crear un arreglo a partir de otro arreglo

import numpy as np

# Arreglo original
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("🔸 Arreglo original:")
print(arr)

# Sacamos una "rebanada" (view)
rebanada = arr[1:, :2]
print("\n🔹 Rebanada (view):")
print(rebanada)

# Modificamos la rebanada
rebanada[0, 0] = 100

print("\n⚠️ Arreglo original después de cambiar la rebanada:")
print(arr)

print("\n🔸 Rebanada actualizada:")
print(rebanada)

#Para no afectar todo, creamos una copia
arr2 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
rebanada_copia = arr2[1:, :2].copy()
print("\n🔹 Rebanada copia (copy):")
print(rebanada_copia)

# Modificamos la copia
rebanada_copia[0, 0] = 100

print("\n✅ Arreglo original después de cambiar la copia:")
print(arr2)

print("\n🔸 Copia actualizada (solo ella cambió):")
print(rebanada_copia)


🔸 Arreglo original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

🔹 Rebanada (view):
[[4 5]
 [7 8]]

⚠️ Arreglo original después de cambiar la rebanada:
[[  1   2   3]
 [100   5   6]
 [  7   8   9]]

🔸 Rebanada actualizada:
[[100   5]
 [  7   8]]

🔹 Rebanada copia (copy):
[[4 5]
 [7 8]]

✅ Arreglo original después de cambiar la copia:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

🔸 Copia actualizada (solo ella cambió):
[[100   5]
 [  7   8]]


In [11]:
#Crear secuencias, repeticiones y números aleatorios

#Sirve para crear una secuencia con paso fijo.
#np.arange(inicio, fin, paso)
import numpy as np
arr = np.arange(0, 10, 2)
print("np.arange(0, 10, 2)")
print(arr)
print()

#np.linspace()
#crea una cantidad exacta de números entre dos valores
#np.linspace(inicio, fin, cantidad)
arr = np.linspace(0, 10, 5)
print("np.linspace(0, 10, 5)")
print(arr)
print()


np.arange(0, 10, 2)
[0 2 4 6 8]

np.linspace(0, 10, 5)
[ 0.   2.5  5.   7.5 10. ]



In [19]:
#Crear arreglos de 1's y 0's
import numpy as np

a = np.zeros((3, 3))
print(a)
print()

b = np.ones((3, 3))
print(b)
print()

#Diagonales
np.fill_diagonal(a, 1)
print(a)
print()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [21]:
# Crear secuencias repetidas

#np.tile()
import numpy as np

a = np.array([1, 2, 3])
print("Original:", a)

# Repite el arreglo 2 veces
b = np.tile(a, 2)
print("Tile:", b)

#np.repeat()
c = np.repeat(a, 4)
print("Repeat:", c)


Original: [1 2 3]
Tile: [1 2 3 1 2 3]
Repeat: [1 1 1 1 2 2 2 2 3 3 3 3]


In [ ]:
#Números aleatorios

In [ ]:
#Elección al azar

In [ ]:
#Semillas

In [ ]:
#Obtener valores únicos y frecuencias absolutas