In [7]:
#Acceder a un elemento dentrode una fila
import numpy as np

arr2 = np.array([[1., 2., 3., 4.],
                 [3., 4., 5., 6.],
                 [5., 6., 7., 8.]])

print(arr2[2,3])

8.0


In [6]:
#Acceder a 1 elemento

import numpy as np

arr2 = np.array([10, 20, 30, 40, 50])
print(arr2[3])


40


In [11]:
#Slice

import numpy as np

arr2 = np.array([[1., 2., 3., 4.],
                 [3., 4., 5., 6.],
                 [5., 6., 7., 8.]])

print(arr2[1:,-2:])


[[5. 6.]
 [7. 8.]]


In [15]:
#Filtrado por condiciones logicas
import numpy as np

arr2 = np.array([[1., 2., 3., 4.],
                 [3., 4., 5., 6.],
                 [5., 6., 7., 8.]])
#AND
print(arr2 > 5)
print()
print(arr2[arr2 > 4])

#OR
print(arr2[(arr2 < 3) | (arr2 > 7)])

#NOT
print(arr2[~(arr2 > 5)])

#COMBINADO
print(arr2[~(arr2 < 4) | (arr2 == 8)])



[[False False False False]
 [False False False  True]
 [False  True  True  True]]

[5. 6. 5. 6. 7. 8.]
[1. 2. 8.]
[1. 2. 3. 4. 3. 4. 5. 5.]
[4. 4. 5. 6. 5. 6. 7. 8.]


In [23]:
#Detectar y reemplazar valores especiales (NaN y inf)
import numpy as np

arr3 = np.array([1, 2, np.nan, 4, np.inf, 5])
print(arr3)
NaN=np.isnan(arr3)   # detecta NaN
Inf =np.isinf(arr3)   # detecta inf
print()
print("NaN: ",NaN)
print("Infinito:",Inf)
print()
#Filtros de sustitucion
arr3[np.isnan(arr3)] = 0
arr3[np.isinf(arr3)] = 999
print(arr3)



[ 1.  2. nan  4. inf  5.]

NaN:  [False False  True False False False]
Infinito: [False False False False  True False]

[  1.   2.   0.   4. 999.   5.]


In [29]:
#Ejercicio de Chat GPT

import numpy as np

arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120],
                [130, 140, 150, 160]])
#Parte A — Accesos directos
#Muestra el elemento que está en la tercera fila y segunda columna.
#Muestra la última fila completa.
print(arr[2,1])
print()
print(arr[-1:,:])
print()
"""Parte B — Slices
Muestra las dos primeras filas y tres primeras columnas.
Muestra las dos últimas columnas de todas las filas."""
print(arr[:2,:3])
print()
print(arr[:,-2:])
print()
"""Parte C — Condiciones
Muestra los valores mayores que 100.
Muestra los valores entre 50 y 120 inclusive.
Reemplaza los valores mayores que 150 por 0."""
print(arr[arr>100])
print()
print(arr[(arr>=50)&(arr<=120)])
print()
arr[arr>150]=0
print(arr)

100

[[130 140 150 160]]

[[10 20 30]
 [50 60 70]]

[[ 30  40]
 [ 70  80]
 [110 120]
 [150 160]]

[110 120 130 140 150 160]

[ 50  60  70  80  90 100 110 120]

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150   0]]
